version: "3"
services:
  postgres:
      image: postgres:latest
      expose:
          - "5432"
      ports:
          - "5432:5432"
      environment:
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_DB=tododuty_db
      restart: always
  backend:
    build:
      context: ./to-do-duty-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
        - postgres
    restart: always
  frontend:
    build:
      context: ./to-do-duty-web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    stdin_open: true
    tty: true